[theme]
background = "default"
primary = "white"
secondary = "black"
title = "blue"
playing = "blue"
playing_bg = "black"
highlight = "light white"
highlight_bg = "red"
error = "light white"
error_bg = "red"
statusbar = "white"
statusbar_progress = "blue"
statusbar_bg = "blue"
cmdline = "light white"
cmdline_bg = "black"
