#!/bin/sh

xrdb ~/.Xdefaults
xcompmgr &
blueman-adapters &
/usr/bin/dunst &
#unity-settings-daemon &
nm-applet &
~/scripts/start_dropbox.sh
clipit &
redshift-gtk &
#fluxgui &
xscreensaver -no-splash &
xpad -N -h &
hamster-indicator &
indicator-sound-switcher &
pasystray &
devilspie -a &

#/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator &
/opt/extras.ubuntu.com/indicator-brightness/indicator-brightness &
google-drive-ocamlfuse -label umich ~/Drive/Umich/
google-drive-ocamlfuse -label merit ~/Drive/Merit/
google-drive-ocamlfuse -label pobox ~/Drive/Pobox/

# /home/schelcj/bin/Nextcloud-2.3.3-x86_64.AppImage &
/home/schelcj/scripts/xscreensaver-watch.sh &
/usr/bin/ssh-add
